### ISSUE TITLE
Is it possible to turn off Mailhog and sending emails?

### ISSUE THREAD

**Issue by zhou9110** [clean-docker/Magento2#100]
Hi, I would like to send emails to some real receivers. And wondering what is the best way to bypass mailhog and send emails via third party SMTP services.

So far I have installed a SMTP module in the Magento store ([magento2-smtp](https://github.com/mageplaza/magento-2-smtp)) and have found the relevant config 
```bash
sendmail_path = "/opt/go/bin/mhsendmail --smtp-addr='mailhog:1025'"
```
in the file in `.docker/config/php.ini` and `/usr/local/etc/php/php.ini` in the container. I am not sure which value what should I change the `sendmail_path` to. 
Any guidance or link to a blog would be appreciated! 😄

**Comment by rafaelstz** [comment]
Hi,
You can do it by commenting this line and restart the container.
