### ISSUE TITLE
Permission /var/www/.composer

### ISSUE THREAD

**Issue by leandrofreire08** [clean-docker/Magento2#16]
Can you provide the root password so we can be able to change permissions for composer cache?

**Comment by leandrofreire08** [comment]
never mind, I just saw that we can specify the user in shell script

**Comment by rafaelstz** [comment]
If you are setting a project in development, you can use this file below to override your **app/etc/env.php** so it'll use the Redis to optimize your installation.

https://github.com/rafaelstz/Magento2Docker/blob/master/env.sample.php
