### ISSUE TITLE
Permissão Pasta

### ISSUE THREAD

**Issue by lukasfeliphe** [clean-docker/Magento2#18]
Rafael,

precisa de alguma permissão específica na pasta? tô tentando subir essa docker, mas quando vai installar o magento dá alguns erros de permissão, e também na hora de rodar o script do redis também dá erro.

Sabe me dizer se qual melhor OS para eu subir ?

**Comment by rafaelstz** [comment]
Olá @lukasfeliphe 
Eu uso no Ubuntu 16.04 e no MacOS High Sierra diariamente são os sistemas que homologuei, em qual OS você está? me passa os comandos e printscreens por aqui que estão dando erro que vejo como posso ajudar.

**Comment by lukasfeliphe** [comment]
Também estou usando o Ubuntu 16.04, mas vou te mandar os prints.

Muito Obrigado Rafael

**Comment by lukasfeliphe** [comment]
Aqui o primeiro erro no ./shell onde aplicando um chmod 777 ele funciona normal
![image](https://user-images.githubusercontent.com/30473853/32187595-b5142740-bd8c-11e7-97aa-5b28696bb3df.png)

por fim acontece esse erro 

![image](https://user-images.githubusercontent.com/30473853/32187838-4b99c8fa-bd8d-11e7-83c7-17ca09e64456.png)


aqui vou instalar o magento..
![image](https://user-images.githubusercontent.com/30473853/32187743-0e55269c-bd8d-11e7-9437-00751072cfdd.png)

**Comment by rafaelstz** [comment]
Estou corrigindo isso no código agora, mas para funcionar nesse container já montado roda esse comando fora do seu container, dentro da pasta clonada:

```bash
sudo rm -rf src/;
sudo mkdir src;
sudo chmod -R u+x $(pwd);
./shell
```

Quando ele acessar seu container usa esse comando:

```bash
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition . ;
php -f ./bin/magento setup:install --base-url=http://localhost/ \
    --db-host=db \
    --db-name=magento \
    --db-user=magento \
    --db-password=magento \
    --admin-firstname=Magento \
    --admin-lastname=Commerce \
    --admin-email=user@example.com \
    --admin-user=admin \
    --admin-password=admin123 \
    --language=en_US \
    --currency=USD \
    --timezone=America/Chicago \
    --use-rewrites=1 \
    --backend-frontname=admin \
    --use-sample-data ;
php -f ./bin/magento indexer:set-mode schedule \
&& cp ~/.composer/auth.json var/composer_home/auth.json \
&& php -f ./bin/magento sampledata:deploy \
&& php -f ./bin/magento setup:upgrade \
&& php -f ./bin/magento indexer:reindex \
&& php -f ./bin/magento cache:flush \
&& php -f ./bin/magento deploy:mode:set production \
&& composer dump-autoload -o ;
mv package.json.sample package.json ; mv Gruntfile.js.sample Gruntfile.js \
&& npm i
```
Quando testar me avisa se deu certo, esses comandos são quase a prova de balas :smile:

**Comment by rafaelstz** [comment]
@lukasfeliphe Corrigido, na sua próxima instalação esse erro já esta corrigido.

**Comment by thiagolima-bm** [comment]
só o root tem permissao na pasta /var/www/html e quando vc usa o comando shell pra instalar o magento, o usuário é o www-data.

**Comment by rafaelstz** [comment]
Apliquei um solução temporária, no seu próximo CURL executado estará corrigido.
Obrigado pelo feedback @thiagolima-bm 😄  👍

**Comment by thiagolima-bm** [comment]
@rafaelstz Parabéns pela iniciativa :)

**Comment by lukasfeliphe** [comment]
@rafaelstz cara deu tudo certo !

Você é F$#@ !

sem mais !!
