### ISSUE TITLE
ServerName

### ISSUE THREAD

**Issue by lukasfeliphe** [clean-docker/Magento2#19]
@rafaelstz só uma questão,

Caso eu queira rodar sem ser em localhost , eu consigo alterar o ServerName para o endereço do site ?

Att

**Comment by lukasfeliphe** [comment]
@rafaelstz 
Cara sou novo no docker então... hehe, 
fiz as alterações que pediu mas não funfou, acredito que devo estar fazendo algo errado no /etc/hosts , lá eu adicionei : 

meuip => dominio.com.br

está certo ? ou tenho que fazer algo mais  ?
Cara não vou mais te encher prometo ... se me ajudar  hahahah

**Comment by rafaelstz** [comment]
@lukasfeliphe tranquilo, meu arquivo `/etc/hosts` está como o printscreen abaixo, só adicionei o **dev.local** que quero usar na frente do **localhost** que já existia.

![image](https://user-images.githubusercontent.com/610598/32450962-d0c2b202-c2fc-11e7-9745-7dd84ca852e9.png)

**Comment by lukasfeliphe** [comment]
@rafaelstz fiz aqui mesma coisa e nada ainda ... aqui está meu /etc/hosts ..
![image](https://user-images.githubusercontent.com/30473853/32452870-e7a04dae-c301-11e7-9012-864835540906.png)
 já atualizei as web/unsecure/base_url e web/secure/base_url

**Comment by rafaelstz** [comment]
Qual url usou no base url?

**Comment by lukasfeliphe** [comment]
Eu usei a url do dominio que eu vou usar a loja .. eu devia deixar o localhost ?

**Comment by rafaelstz** [comment]
Nesse caso acrescentamos o dev.local como um dominio adicional, então funcionaria ou em **http://localhost/** ou **http://dev.local/**
Se você não for usar o **dev.local** pode colocar seu dominio que usou como base url no lugar dele no `/etc/hosts`.

**Comment by lukasfeliphe** [comment]
Então eu fiz isso mesmo assim nada, o mais engraçado que se eu coloco meudominio.com:8080 ele acessa o php normal, o mailhog também, é apenas o magento mesmo que não acessa 👎

**Comment by rafaelstz** [comment]
Tenta ao invés de add o dominio depois do localhost adicionar em uma linha antes com o valor:
127.0.0.1        meudominio.com www.meudominio.com
