### ISSUE TITLE
.npm and .composer folder permissions

### ISSUE THREAD

**Issue by rorteg** [clean-docker/Magento2#22]
Linux dist: Fedora

When running the command to install Magento, there were some problems with creating the Composer cache folder and at the end several errors related to NPM.

This is why when installing Magento we are using the "www-data" user privileges and the folder /var/www/.npm and /var/www/.composer are the user "root"

I solved only with these two commands:
```
docker-compose exec --user root apache chown www-data:www-data /var/www/.npm -Rf
docker-compose exec --user root apache chown www-data:www-data /var/www/.composer -Rf
```
 I believe you can implement a better solution directly in DockerFile.

Thanks for sharing this solution.

**Comment by RogerKeulen** [comment]
Yes, had the same problem. After executing your 2 commands on my local machine, i got the integration tests to work. ;-)

**Comment by rafaelstz** [comment]
Done @rorteg @RogerKeulen, your next **CURL** will include the fix.
