### ISSUE TITLE
How to change the directories being synced

### ISSUE THREAD

**Issue by jwohlfeil** [clean-docker/Magento2#38]
I'm trying to sync the vendor dir, so i removed the corresponding lines in docker-sync.yml, stopped and started the containers again, but the changes have no effect. How can I achieve this?

**Comment by jwohlfeil** [comment]
Ok, found something here in Kitematic Settings of the Sync Container: http://take.ms/XlrVZ

**Comment by rafaelstz** [comment]
Thanks for the report!
![image](https://user-images.githubusercontent.com/610598/36335181-2622b054-1365-11e8-9b67-a05e5ec1d680.png)
