### ISSUE TITLE
SQLSTATE[HY000] [1045] Access denied for user 'magento'@'172.20.0.7' (using password: YES)

### ISSUE THREAD

**Issue by duytran21** [clean-docker/Magento2#42]
After I do install-magento2 It gives me this error. Do you know how to fix it? I'm newbie in magento and docker

Thanks

**Comment by rafaelstz** [comment]
Hi @duytran21, you can run these commands below after running the commands `./shell` to access your container:

```
composer install
chmod u+x ./bin/magento
n98 db:drop && n98 db:create && rm app/etc/env.php
n98 setup:install --base-url=http://localhost/ \
    --db-host=db \
    --db-name=magento \
    --db-user=root \
    --db-password=root \
    --admin-firstname=Magento \
    --admin-lastname=Commerce \
    --admin-email=user@example.com \
    --admin-user=admin \
    --admin-password=admin123 \
    --language=en_US \
    --currency=USD \
    --timezone=America/Chicago \
    --use-rewrites=1 \
    --backend-frontname=admin \
    --use-sample-data \
&& n98 sampledata:deploy \
&& n98 setup:upgrade \
&& n98 indexer:reindex \
&& n98 cache:flush;
mv package.json.sample package.json ; mv Gruntfile.js.sample Gruntfile.js;
npm i;
n98 deploy:mode:set developer;
```

What's your OS? have you specified some version when install using `install-magento2`?

**Comment by duytran21** [comment]
I'm using Mac High Sierra now. 
Yes, I did install-magento2 2.2.3

**Comment by rafaelstz** [comment]
@duytran21  Is it working after run the code snippets above?

**Comment by duytran21** [comment]
Thank you for your response.
I don't use docker to install magento anymore. I built it on cloud server.
Anyway thanks again. I really appreciate it.
