### ISSUE TITLE
docker-sync stops working after some idle time

### ISSUE THREAD

**Issue by jwohlfeil** [clean-docker/Magento2#45]
When i start or stop and the start the containers everything works as expected. But after some idle time (approx. 3 or 4 minutes) further changes in the file system are not noticed anymore. In the daemon.log i connot find any hints why it's not working... any ideas?

**Comment by rafaelstz** [comment]
Hi @jwohlfeil , thank you for your feedback!

It's happening when there are many files syncing at the same time, like the folder **pub/, var/** or **generated/**.
So, I ignored these folders on file: https://github.com/clean-docker/Magento2/blob/mac/docker-sync.yml

You can check this file on Mac or use these commands as well:

```
./stop
docker-sync clean
./start
docker-sync sync && docker-sync log
```

If it works, please let me know!

**Comment by jwohlfeil** [comment]
Doesn't work, sync keeps completely unstable. So i have to stop and start the instances over and over again to get the system synced - terrible workflow... any other ideas? Setting it up newly and install my magento installation again?

**Comment by rafaelstz** [comment]
I had had a similar issue, so I fixed updating the **docker-sync**, **unison** and **Docker Eugene image** using these commands below:

```
brew update ; brew install unison ; brew upgrade unison
gem install docker-sync
docker pull eugenmayer/unison:2.51.2.0
./stop && docker-sync clean && ./start
```
If it works, please let me know!
Thanks

**Comment by jwohlfeil** [comment]
Thank you! Looks better now. I'll know more when I work on it the next time.
