### ISSUE TITLE
PHPstorm config / empty vendor folder

### ISSUE THREAD

**Issue by perrivdb** [clean-docker/Magento2#47]
I installed this Magento 2 Docker container, it runs very fast on the basic Luma theme. 
However, I can't make any changes to files, as the vendor folder is empty in phpstorm.

Did I setup the project incorrectly?

**Comment by rafaelstz** [comment]
Check you [Docker-sync](https://github.com/clean-docker/Magento2/blob/mac/docker-sync.yml) file, check if your vendor folder is commented, if yes use uncomment and use these commands:

    ./stop && docker-sync clean && ./start
