### ISSUE TITLE
What is the root password?

### ISSUE THREAD

**Issue by beauzeph** [clean-docker/Magento2#49]
I installed this and got Magento2 up and going.  Thank you.

I copied an app folder into the root directory because I am installing a plugin.  For some reason teh shell and Magento are unable to read the contents of this folder.

I'm trying to troubleshoot the issue.  I am trying to run this command: su -c "setenforce 0"

But I'm being prompted for the root password.  What is the root password for this container?  I've tried admin and root but no luck.  Thank you

**Comment by rafaelstz** [comment]
Hi @beauzeph,

As you are locally, out of your container run these commands below:

```
sudo chmod -R 777 src/;
./stop && ./start && ./shell
```

Please, let me know if it worked!
