### ISSUE TITLE
 Authentication required (repo.magento.com) what does it mean?

### ISSUE THREAD

**Issue by Abunwer** [clean-docker/Magento2#50]
I typed 
install-magento2  
then ask me for a username and password 
what is the username and the password ?

**Comment by rafaelstz** [comment]
You need to get the user and pass directly on the Magento Marketplace account.
https://devdocs.magento.com/guides/v2.2/install-gde/prereq/connect-auth.html

![cloud_access-key](https://user-images.githubusercontent.com/610598/39652223-3b1de506-4fc3-11e8-8853-4f5e49319194.png)

**Comment by Abunwer** [comment]
Thank you that resolve my issue
