### ISSUE TITLE
Sobre o uso de link simbólico

### ISSUE THREAD

**Issue by mozgbrasil** [clean-docker/Magento2#51]
Boa Tarde

Sobre o uso de link simbólico

Conforme imagens

Vemos que não está funcionando a exibição do link simbólico

Veja que no host eu criei um arquivo fisico e um link simbolico na pasta "src" do Container, mas somente o arquivo fisico é exibido

Pode me ajudar ?

-

![captura de tela de 2018-05-10 21-43-04](https://user-images.githubusercontent.com/17202780/39900977-e01b8fe0-549b-11e8-978c-b6980f4dcb26.png)
![captura de tela de 2018-05-10 21-43-35](https://user-images.githubusercontent.com/17202780/39900978-e042d10e-549b-11e8-8293-b21b4dfb7e3d.png)

**Comment by rafaelstz** [comment]
Olá @mozgbrasil ,

Estou pesquisando sobre isso, mas me parece que isso é uma questão nativa do Docker que precisa ser resolvida.

Att.
Rafael

**Comment by mozgbrasil** [comment]
Boa Tarde

A solução está registrada em 

https://github.com/cytopia/devilbox/issues/90
