### ISSUE TITLE
can I rebuild the image so I can integrate an extension?

### ISSUE THREAD

**Issue by jegacs** [clean-docker/Magento2#59]
I see that in the src directory is the source code of magento. How could I rebuild the image in order to add modified source code I want to test? This is because I want to test an integration. 
Thanks.

**Comment by jegacs** [comment]
Im using Ubuntu 18.04. You mean src folder outside the magent docker image?

**Comment by rafaelstz** [comment]
You can add new files directly into your `src` folder, this folder in sync with your container.
