### ISSUE TITLE
A question: Sudo rights?

### ISSUE THREAD

**Issue by wirdehall** [clean-docker/Magento2#60]
Hello, I'm on mac OS and I want to start with saying this package is awesome.
Now to the question: When I use the install script: `curl -s https://raw.githubusercontent.com/clean-docker/Magento2/master/init | bash -s MYMAGENTO2 clone`
I get prompted for sudo twice during the installation, i canceled both of them and the installation continues and the project still seams to work.

My question, why does it need sudo rights? And also, am I missing something since i didn't provide sudo access?

**Comment by rafaelstz** [comment]
The SUDO is requested to set the permission to the folder, if the project is running well, you don't need to worry about it.
