### ISSUE TITLE
How enable mysqli?

### ISSUE THREAD

**Issue by Nerjuz** [clean-docker/Magento2#76]
How I can enable mysqli for php? 
I try to use direct sql query calls but got error.

`Fatal error: Uncaught Error: Call to undefined function mysqli_connect() `

**Comment by JackWormUK** [comment]
have you checked that the PHP extension is installed?

[https://stackoverflow.com/questions/7250356/how-to-install-mysqli](https://stackoverflow.com/questions/7250356/how-to-install-mysqli)
