### ISSUE TITLE
n98-magerun2 is broken

### ISSUE THREAD

**Issue by lamador1980** [clean-docker/Magento2#80]
Not sure why, but after I installed a new instance of Magento 2.3.X, I tried running  n98-magerun2 and it was broken.

![screen shot 2019-01-24 at 9 33 06 am](https://user-images.githubusercontent.com/46786481/51684978-4ea08980-1fbb-11e9-9f02-f6db78239207.png)

Maybe the n98-magerun2 version is older but once I went to the n98-magerun2 Github page and curled another download of n98-magerun2, it worked again.

![screen shot 2019-01-24 at 9 37 03 am](https://user-images.githubusercontent.com/46786481/51685122-a50dc800-1fbb-11e9-9951-980d7af9afd1.png)

**Comment by rafaelstz** [comment]
It was a Magerun's incompatibility, the container uses the last version when created.
The current version supports Magento 2.3, to run the command update, run:

```bash
n98 selfupdate
```
