### ISSUE TITLE
How can i change domain

### ISSUE THREAD

**Issue by mrtuvn** [clean-docker/Magento2#87]
Instead localhost i would like to change to my own style domain. Ex magento2.test
How can i do that
I mean possible to let config domain before init container ?

**Comment by MrLuisAmador** [comment]
Here's the file you would have to edit to update the flag that sets your URL. I wouldn't advise modifying core files. You can update the URL easily in the Admin once the local website is up.

https://github.com/clean-docker/Magento2/blob/master/.docker/bin/install-magento2

<img width="671" alt="Screen Shot 2019-04-22 at 11 42 20 PM" src="https://user-images.githubusercontent.com/6766589/56552277-c51c3b80-6558-11e9-8f75-219c2ed09c18.png">
