### ISSUE TITLE
Do not Composer as roo/super user!

### ISSUE THREAD

**Issue by vpcarlos** [clean-docker/Magento2#89]
I tried to run command` install-magento2`, and shell throws **Do not Composer as roo/super user!**

**Comment by vpcarlos** [comment]
Solved

**Comment by zhaojc** [comment]
i got some error as below?could you help me to slove it ?thank u 

www-data@0fd29b507713:~/html$ install-magento2
Installing magento/project-community-edition (2.3.1)

                                      
  [InvalidArgumentException]          
  Project directory ./ is not empty.  
                                      

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

chmod: cannot access './var': No such file or directory
chmod: cannot access './vendor': No such file or directory
chmod: cannot access './pub/static': No such file or directory
chmod: cannot access './pub/media': No such file or directory
chmod: cannot access './app/etc': No such file or directory
'/var/www/env.sample.php' -> './app/etc/env.php'
cp: cannot create regular file './app/etc/env.php': No such file or directory
/usr/local/bin/install-magento2: line 27: n98: command not found
Could not open input file: ./bin/magento
cp: cannot create regular file 'var/composer_home/auth.json': No such file or directory
mv: cannot stat 'package.json.sample': No such file or directory
mv: cannot stat 'Gruntfile.js.sample': No such file or directory
npm WARN enoent ENOENT: no such file or directory, open '/var/www/html/package.json'
npm WARN html No description
npm WARN html No repository field.
npm WARN html No README data
npm WARN html No license field.
Could not open input file: ./bin/magento
www-data@0fd29b507713:~/html$ exit

**Comment by vpcarlos** [comment]
Hi, try **to remove** entire project, you can try this:
 - docker-compose down -rmi all -v --remove-orphans
 - docker system prune -a

Now try **to install** it again:
 - curl -s https://raw.githubusercontent.com/clean-docker/Magento2/master/init | bash -s 
   MYMAGENTO2 clone
- cd MYMAGENTO2
- ./shell
- rm index.php
- install-magento2

![image](https://user-images.githubusercontent.com/45365768/59085605-70adff00-88ff-11e9-9a5d-9f1725969f77.png)
