### ISSUE TITLE
Is possible to create subdomain working along with main domain ?

### ISSUE THREAD

**Issue by mrtuvn** [clean-docker/Magento2#99]
Some case i want to create subdomain to work with main domain magento
Example
Main domain: https://main.store/index.php
sub domain: https://sub.main.store/index.php

**Comment by NathanDayMF** [comment]
- Add a New Website/StoreView/Store as per normal Magento Processes and as per your requirements
- get the Docker Conatiner IP with `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <conatiner_id>`
- Add this to your Hosts File (`/etc/hosts` on Linux) along with your custom domain name
- Set the Base URL for your New Website/Storeview/Store
